name: Build & Release 

on:
  push:
    branches: [ main ]
    tags:    [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write   # allow creating/updating Releases & uploading assets
  actions:  read    # allow pulling marketplace actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CC: gcc
  CXX: g++
  UPLOAD: ${{ secrets.UPLOAD }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
  STORE_FILE: ${{secrets.STORE_FILE}}
  KEY_ALIAS: ${{secrets.KEY_ALIAS}}

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Submodule Init
        uses: snickerbockers/submodules-init@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Android build-tools
        run: |
          $ANDROID_HOME/cmdline-tools/16.0/bin/sdkmanager "build-tools;34.0.0"
          echo "$ANDROID_HOME/build-tools/34.0.0" >> "$GITHUB_PATH"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: 3.38.7
      - run: echo $UPLOAD | base64 -di > android/app/release.jks
      - run: |
          printf "storePassword=$STORE_PASSWORD\n" > ./key.properties
          printf "keyPassword=$KEY_PASSWORD\n" >> ./key.properties
          printf "keyAlias=$KEY_ALIAS\n" >> ./key.properties
          printf "storeFile=android/app/release.jks\n" >> ./key.properties
      - run: flutter upgrade
      - run: flutter clean
      - run: flutter pub get
      - run: mkdir -p artifacts
      - name: Build APK
        run: |
          flutter build apk --release
          cp build/app/outputs/flutter-apk/app-release.apk artifacts/wrsim.apk
      - name: Build APK arm
        run: |
          flutter build apk --release --split-per-abi --target-platform="android-arm" 
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk artifacts/wrsim-armeabi-v7a.apk
      - name: Build APK arm64
        run: |
          flutter build apk --release --split-per-abi --target-platform="android-arm64" 
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk artifacts/wrsim-arm64-v8a.apk
      - name: Build APK armx86_64
        run: |
          flutter build apk --release --split-per-abi --target-platform="android-x64" 
          cp build/app/outputs/flutter-apk/app-x86_64-release.apk artifacts/wrsim-x86_64.apk


      # ─────────────── ONLY ON TAGS ───────────────
      - name: Create or update Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1.16.0
        with:
          tag:       ${{ github.ref_name }}
          name:      Release ${{ github.ref_name }}
          artifacts: artifacts/*.apk
          token:     ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "body.md"
          allowUpdates: true

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Submodule Init
        uses: snickerbockers/submodules-init@v4
 
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter clean
      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter build windows --release
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp -r build\windows\x64\runner\Release\ artifacts/
          cd artifacts
          tar -acf wrbattlesim.zip .

      # ─────────────── ONLY ON TAGS ───────────────
      - name: Create or update Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1.16.0
        with:
          tag:       ${{ github.ref_name }}
          name:      Release ${{ github.ref_name }}
          artifacts: artifacts/*
          token:     ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "body.md"
          allowUpdates: true

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Submodule Init
        uses: snickerbockers/submodules-init@v4
   
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: set env
        run: echo "CMAKE_CXX_COMPILER=/usr/bin/g++" >> $GITHUB_ENV
      - run: |
          sudo apt-get update -y
          sudo apt install -y clang cmake ninja-build libgtk-3-dev
      - name: Doctor
        run: flutter doctor
      - run: flutter upgrade
      - name: Build
        run: flutter build linux
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp -r build/linux/x64/release/bundle/* artifacts/
          cd artifacts
          tar -czf wrbattlesim.tar.gz *

      # ─────────────── ONLY ON TAGS ───────────────
      - name: Create or update Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1.16.0
        with:
          tag:       ${{ github.ref_name }}
          name:      Release ${{ github.ref_name }}
          artifacts: "artifacts/*.tar.gz"
          token:     ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "body.md"
          allowUpdates: true
